"""empty message

Revision ID: 31a9568c7a2f
Revises: d2fe9d7b3770
Create Date: 2022-06-16 19:37:40.135540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31a9568c7a2f'
down_revision = 'd2fe9d7b3770'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('image_status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'image_status')
    # ### end Alembic commands ###
