"""empty message

Revision ID: af73df72263f
Revises: 43a8624a522e
Create Date: 2022-06-02 19:41:45.308362

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'af73df72263f'
down_revision = '43a8624a522e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('queue', 'date',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_column('queue', 'time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queue', sa.Column('time', mysql.DATETIME(), nullable=False))
    op.alter_column('queue', 'date',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
